### ISSUE TITLE
Combining styles in text label tags

### ISSUE THREAD

**Issue by mendelsimon** [dsafa/audio-band#107]
When using styles in text label tags, only one can be applied at once. There does not appear to be a way to combine styles, e.g. to make text both **bold** ***and*** *italic*. Trying to use multiple style modifiers, e.g. {*&artist} simply results in only the final modifier working.
It would be nice if they could be combined.

--
*@dsafa Thank you for all your work on this great project! 
I'm offering a couple suggestions now because I saw you started a new __UI controls updates__ Github project.*

**Comment by dsafa** [comment]
Closing finished issues (v0.9)
