### ISSUE TITLE
RegAsm : error RA0000 : Unable to locate input assembly 'C:\Users\Joseph\Desktop\audio-band-master\tools\AudioBand.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by X33NO** [dsafa/audio-band#112]
The title is what i get, it did not download a dll apparently

**Comment by dsafa** [comment]
Did you download it from the project page? You should be downloading it from [here](https://github.com/dsafa/audio-band/releases).

**Comment by X33NO** [comment]
now I'm getting this: RegAsm : warning RA0000 : Registering an unsigned assembly with /codebase can cause your assembly to interfere with other applications that may be installed on the same computer. The /codebase switch is intended to be used only with signed assemblies. Please give your assembly a strong name and re-register it.
RegAsm : error RA0000 : An error occurred while writing the registration information to the registry. Administrator permissions are needed to use the selected options. Use an administrator command prompt to complete these tasks.
Press any key to continue . . .
