### ISSUE TITLE
Audio Band won't start

### ISSUE THREAD

**Issue by agiovinazzi** [dsafa/audio-band#114]
Hi, yesterday I've tried to install Audio Band for the first time. I've followed the instructions, the toolbar is showing but when I click on Audio Band settings, nothing appears. Also, Audio Source not showing anything. I've altready tried to uninstall and reinstall and the .net framework is updated.

Here's the log: 
[AudioBand.log](https://github.com/dsafa/audio-band/files/2955743/AudioBand.log)

Thanks a lot!

**Comment by dsafa** [comment]
You need to unblock the files. `MahApps.Metro.IconPacks.Material.dll` and maybe others.

**Comment by agiovinazzi** [comment]
Thanks, now it works.
