### ISSUE TITLE
Audioband not working

### ISSUE THREAD

**Issue by Zerkzyy** [dsafa/audio-band#115]
After I installed I placed the utility on my Taskbar but when I hover over audio source option I don't get anything. I am not very good with this stuff but I can follow specific instructions. I read the last comment pertaining to this issue and did as you said. I ran the Unblock script but still no fix.

**Comment by Zerkzyy** [comment]
Also is there any way to stop the process so I can delete the folder to attempt to re-install from step one?

**Comment by dsafa** [comment]
Run the uninstall and then restart explorer. Some files are probably still blocked so try unblocking the zip file itself and re-extract the files, then install. If that works, I'll update the documentation to make it better.
