### ISSUE TITLE
Defaults to Music Bee when PC starts up

### ISSUE THREAD

**Issue by MrJozroz** [dsafa/audio-band#120]
A while ago Audio Band started defaulting to Music Bee whenever I start my computer.

I'm not sure what is causing it, the only suspicion I have is that it happened a short while after I tried installing Music Bee to try it out with Audio Band, though I could never get it to work and simply left it at that. Since then I have to manually switch to Spotify every time I start my PC.
 
EDIT: This also happens when waking the computer from sleep mode.

**Comment by dsafa** [comment]
It might be because it is not properly saving the last audio source you used. Try just opening the settings window and pressing save. That should force everything to save.

**Comment by MrJozroz** [comment]
That did the trick, thanks!

**Comment by dsafa** [comment]
Awesome. I'll update it so that it saves the current audio source right away.

**Comment by dsafa** [comment]
Closing old issue. Should work properly now.
