### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [dsafa/audio-band#123]
Hi @dsafa I am a graphic designer and opensource enthusiast, I wanted to contribute to your project and i've designed a logo for your project. If you need something else please let me know. Regard! 
![audio band](https://user-images.githubusercontent.com/36124339/56013784-acbc4d80-5d1c-11e9-83e2-d5f4fb671e90.png)

**Comment by dsafa** [comment]
Thanks! This is awesome. I haven't worked with logos, what are the licenses/credits to use it?

**Comment by mirzazulfan** [comment]
Thanks for your response, I'm glad you liked it. This logo is free, I like to create logos for open source projects. What color do you prefer? 

#### Licence
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
</center>

**Comment by dsafa** [comment]
Thanks! I think blue looks fine.

**Comment by chippleh1392** [comment]
Just want to comment that this looks great. Great job Mirza!

**Comment by mirzazulfan** [comment]
Thanks guys. I've created a pr #124. If you need help in the future, don't hesitate to contact me. Best Regard.

**Comment by dsafa** [comment]
Thanks again!
