### ISSUE TITLE
Audio Source not showing spotify on list

### ISSUE THREAD

**Issue by matallica81** [dsafa/audio-band#13]
When I hover over the audio source option, no popout menu to select Spotify as audio source appears.

**Comment by matallica81** [comment]
I just read through the other issue thread and see you're currently working on fixing this. Thank you for making this by the way!

**Comment by madcaddies420** [comment]
Me aswell!  If needed, I can provide more information.

**Comment by Biiox** [comment]
Duplicate of #3

**Comment by dsafa** [comment]
Thanks for reporting.
