### ISSUE TITLE
Windows dark theme not supported (0.9.0 - pre1)

### ISSUE THREAD

**Issue by ingdanko** [dsafa/audio-band#158]
**Describe the bug**
^^ title

**To Reproduce**
1. Windows search
2. "Colors"
3. All the way down is "Choose your default app mode" 
4. Dark
5. Go to Audio Band settings
6. Most of the colors are messed up

**Screenshots**
![image](https://user-images.githubusercontent.com/20192832/57954050-21714180-78f2-11e9-99c5-3a309b91baab.png)
![image](https://user-images.githubusercontent.com/20192832/57954065-2afaa980-78f2-11e9-823e-6a86ce50bf52.png)

**Version Info**
 - Windows 10 Home 1803
 - AudioBand Version [e.g. 0.9.0]

**Comment by dsafa** [comment]
Closing fixed issue
