### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by swashbucklinman** [dsafa/audio-band#16]
I followed the installation instructions and the toolbar doesn't seem to be working at all, even with Spotify selected as the audio source. I'm using the latest version of Audio Band and Spotify downloaded from the Windows Store on Windows 10 64 bit. Excuse me for the lack of info with this post, I'd provide a log file but I can't seem to find one.

Edit: Just tried using the Spotify 64 bit version not on the Windows store, still no dice. Any ideas?

**Comment by lazyb5** [comment]
Spotify broke the API used by most programs displaying spotify info.

**Comment by dsafa** [comment]
Thank you, that is correct. I've created an issue to inform other people 
#17
