### ISSUE TITLE
Scrolling text starting position (0.9.0 - pre1)

### ISSUE THREAD

**Issue by ingdanko** [dsafa/audio-band#161]
When the text begins to scroll (for example when you set it to scroll on mouse over), the scroll starts at the far right of the text rect. I think it would make much more sense if it just started scrolling from where the text was.

What it does now:
![9535b9d8-8891-4c20-8fa3-17f593d2d147](https://user-images.githubusercontent.com/20192832/57955035-fb00d580-78f4-11e9-93f4-aabd08e3d2c3.gif)

What i think it should do:
![c8be6def-95e5-4759-b050-e19d3dda4fdc](https://user-images.githubusercontent.com/20192832/57954954-bc6b1b00-78f4-11e9-861a-9027b75e6d3d.gif)

PS: I'm not sure what to categorize this as. A suggestion maybe?

**Comment by dsafa** [comment]
Thats what the original behaviour was supposed to be but it was much easier to just scroll from the edge. Probably re-visit it in the future.

**Comment by dsafa** [comment]
Well never mind, it was simpler to do than what I originally thought.
