### ISSUE TITLE
Version 0.9.0 can mess up Windows 8 explorer (or lower I assume)

### ISSUE THREAD

**Issue by Waliactico** [dsafa/audio-band#167]
Tried installing v0.9.0 in my Windows 8.1, and explorer started rebooting itself nonstop.
I assume only Windows 10 is supported, but this can cause serious trouble if installed in other versions.

Solution to revert, as explorer is not accessible any more:
- Open Task manager (ctrl + shift + esc)
- While holding down Ctrl key, click File -> Start new task. This will open cmd with admin privileges
- Navigate to Audioband v0.9.0 folder
- Run uninstall.cmd

[AudioBand.log](https://github.com/dsafa/audio-band/files/3211908/AudioBand.log)

Given this, I can't use Audioband 0.9.0 in Windows 8.1. Will successive versions be available for other versions of Windows?

**Comment by dsafa** [comment]
I should be more clear about the requirements. Its only for windows 10 now. That said, all essential features should work non windows 10 versions. I have fallbacks in place if the windows version doesn't match so there is probably something that I forgot to check.

**Comment by dsafa** [comment]
I took a look at the logs and the crashing is due to a different issue

**Comment by Waliactico** [comment]
So it's not about being Windows 8? Sorry then about the wrongly named report. Nevertheless, it's a dangerous bug, as it can render Windows unusable if someone don't know how to fix it

**Comment by dsafa** [comment]
Well, there were other issues that can cause crashing for non windows 10 that I think i've fixed. As for the continuous crashing, I will see what I can do to detect loops.

**Comment by Jokis94** [comment]
Hello there, i experienced same problem but on W10 platform.
Only solution for this was to restart server in spotify developer app. It seemed like it could connect with wrong authentication. 

[AudioBand.log](https://github.com/dsafa/audio-band/files/3391635/AudioBand.log)
Translation:
(Vstupní řetězec nemá správný formát. (Input string format is wrong))
In general good work there. Happy to see so active developers such as yourself :) Do you mind adding one popup window when it will do same problem? Like question that something happened and ask if i want to reset toolbar for fresh start. Cause when this happened it was nightmare to operate. Only way i could stop this behaviour was restarting server in spotify developer. Couldn´t close process in Task manager.

**Comment by dsafa** [comment]
I'll get something done about it asap.
