### ISSUE TITLE
IMPORTANT! Currently cannot display song information for Spotify

### ISSUE THREAD

**Issue by dsafa** [dsafa/audio-band#17]
Spotify has broken the api used to get song information from the desktop player.
More information can be found [here](https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/254)

**Comment by swashbucklinman** [comment]
Damn, still gonna keep development up?

**Comment by dsafa** [comment]
I will. The Spotify issue should only be temporary and I've got plans for other music players.

**Comment by swashbucklinman** [comment]
Thanks, I appreciate your work!

**Comment by dsafa** [comment]
I've updated it with a workaround for now. Thanks to someones suggestion,  I grab the song information from the title of the Spotify window. This means there is no album art and no song progress, but everything mostly works the same.

For the future, It will be using the official Spotify web Api, but that will take some time to implement

**Comment by swashbucklinman** [comment]
Thanks!!

**Comment by dsafa** [comment]
Finally fixed it in #32. Still some issues, I've posted a discussion here #39
