### ISSUE TITLE
4K Support

### ISSUE THREAD

**Issue by horseheadtv** [dsafa/audio-band#18]
My XPS 15 has a 4k screen, so it doesn't show correctly.
![capture](https://user-images.githubusercontent.com/19293993/44550140-f6521c80-a6e8-11e8-8a01-c1eb89695a24.PNG)

**Comment by SAMUD** [comment]
My PC also has a 4K screen. So 4K support would be cool

**Comment by dsafa** [comment]
I had some issues with dpi support so I've put it on hold for now. For now, you can manually change the size so that it fits correctly.
