### ISSUE TITLE
No track information is displayed.

### ISSUE THREAD

**Issue by OrionFalls** [dsafa/audio-band#186]
After the last windows update (not sure exactly because of this), now playing information, cover and progress bar is no longer displayed. Only the next / previous track buttons work. I tried to roll back to the previous versions of the audio band, deleting completely old ones, and set up again the audio sources. Nothing helps. Spotify client id and secret is right. Has anyone encountered a similar problem?
AudioBand version: 0.9.1
Windows 10 version: 1903, build 18362.145

![Annotation 2019-06-06 092108](https://user-images.githubusercontent.com/35342546/59012128-675d5d80-883f-11e9-8b8f-8acef5e52a56.jpg)
[AudioBand.log](https://github.com/dsafa/audio-band/files/3260279/AudioBand.log)

**Comment by dsafa** [comment]
On 1903 i've had windows not connect to the internet right away which it does not account for. You could try to open the settings file %appdata%/AudioBand/AudioBand.settings and delete everything below and including the line that says [[AudioSourceSettings]] then restart audioband. That will completely reset all audio source settings. Other than that, I'm not seeing anything else in the logs.

**Comment by OrionFalls** [comment]
did not help =(

**Comment by dsafa** [comment]
hmm, I don't see any thing else that could be an issue. Do you have another device you can test on? You could also try resetting it again but create a different spotify app and use that client id/secret instead.

**Comment by OrionFalls** [comment]
At the moment there is no possibility to test on another device. I tried to create a new app, the result is the same

**Comment by dsafa** [comment]
Can you post the logs again, there might be new information now. I initially thought that the windows update might have blocked it or something but I don't think that is the case. I'll see if I can create a temp version for you that has more diagnostics.

**Comment by OrionFalls** [comment]
[AudioBand.log](https://github.com/dsafa/audio-band/files/3274870/AudioBand.log)
Once again I tried to return to the preview version 1 with manual installation. But nothing new.

> I'll see if I can create a temp version for you that has more diagnostics.

It would be great!

**Comment by OrionFalls** [comment]
After reinstalling the spotify, everything works fine, but after a reboot, the problem returns every time.

**Comment by dsafa** [comment]
What do you mean by reinstalling spotify. Just resetting the client id?

**Comment by OrionFalls** [comment]
I mean reinstalling spotify desktop application

**Comment by dsafa** [comment]
Hmm strange. I guess post more logs?
Any more details? Does reinstalling spotify get track information to start displaying again right away without having to do anything else.

**Comment by OrionFalls** [comment]
> Does reinstalling spotify get track information to start displaying again right away without having to do anything else.

exactly. But after reboot only next\previous buttons work. 
[AudioBand.log](https://github.com/dsafa/audio-band/files/3303381/AudioBand.log)

**Comment by dsafa** [comment]
Do you have private session enabled in spotify? I looked at the docs and apparently Spotify will not report any track data if that option is enabled.

**Comment by OrionFalls** [comment]
No, private session is disabled

**Comment by dsafa** [comment]
Ok, I created a temp version that has some extra logging to see if it helps. Try using that version and upload the new logs. You'll probably have to uninstall the current version.

[AudioBand.zip](https://github.com/dsafa/audio-band/files/3311714/AudioBand.zip)

**Comment by OrionFalls** [comment]
So, I deleted the previous version and installed yours. Here is new log
[AudioBand.log](https://github.com/dsafa/audio-band/files/3313052/AudioBand.log)

**Comment by dsafa** [comment]
Seeing some 502 http errors and weird socket connection issue which seems to indicate something wrong on spotify's side. I don't see any reports on the spotify web-api github repo though. 
Sorry to ask for logs again 😅 but I can't really figure out anything right now with what information I have and no else seems to be having the same issue. Can you upload the logs a bit after it starts working again, maybe there is something triggered by reinstalling.

**Comment by OrionFalls** [comment]
idk how, but now audioband works perfectly again O_o
I did not install anything new and did not reinstall the old, it just worked. Anyway, here are the new logs. I hope this problem will not happen again =)
[AudioBand.log](https://github.com/dsafa/audio-band/files/3319415/AudioBand.log)

**Comment by OrionFalls** [comment]
This is crazy, but it stopped working again.d
[AudioBand.log](https://github.com/dsafa/audio-band/files/3320508/AudioBand.log)

**Comment by dsafa** [comment]
Well good or bad news is that it's as I thought, Spotify is just not sending any track information to you for some reason. And then sometimes it decides to work work haha. At this point I don't have much else to help fix this issue. Might have to dig around a bit more. Do you think it could be some specific songs that just don't work?

**Comment by OrionFalls** [comment]
No, the reason is definitely not in specific songs. If I reinstall Spotify, then everything works fine. But after rebooting, even including the same songs, it does not work again.
And I noticed one very strange thing - when I turn on the web player, the information from it is displayed in the audioband. But the forward / backward buttons act on the Spotify desktop app. That is, the standalone and web versions work separately, although everywhere one account and before they worked as one unit. Maybe the problem in that?

**Comment by OrionFalls** [comment]
After some experiments, I can say that the problem is on the side of the spotify. Something is wrong with my account settings i guess. Because after a fresh installation in the "Devices Available" menu, I see all my devices and everything works like a charm. But after rebooting, this menu is empty and the audioband just stops working.

**Comment by dsafa** [comment]
That's interesting.I've Never looked at spotify's files. I searched it up and it seems like it is for A/B testing. Maybe your account has a feature that Spotify is testing and it is interfering with something. I guess you could try creating a new temp account and see how that works out.

About the forwward/backwards buttons. I just use the desktop app to control forwards and backwards cause its faster than doing it over the web. Might remove it in the future so that there doesn't have to be a dependency on the desktop app.

**Comment by OrionFalls** [comment]
I created a bat file that deletes abba.json automatically when the system boots. Maybe in the future I will try to create a new account and test it on it. But at the moment this is enough for me, so I close the issue. Thank you very much for participating!
