### ISSUE TITLE
Missing image files causing crash loops

### ISSUE THREAD

**Issue by Biiox** [dsafa/audio-band#192]
It took me a long time figuring out what was causing audioband to crash repeatedly, apparently if you set an image path for the buttons and rename / delete it when the program would load it would crash windows explorer,

Had ver 8.0 updated to 9.1 when it happened
Log:
[AudioBand.log](https://github.com/dsafa/audio-band/files/3319110/AudioBand.log)

My discord if you need any more info: Biiox#1485

Edit: Also button images are global and aren't saved between profiles

**Comment by dsafa** [comment]
My bad, thats what happens when I don't have enough tests. I'll get it fixed.
