### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by medifin** [dsafa/audio-band#2]
Freezes occasionally and need to re-apply audio source.

**Comment by dsafa** [comment]
1. Which version of audio-band are you running?
2. Is there a trigger for the freeze (switching songs, reopening spotify, etc...)

It would make it easier to track down the issue, thanks.

**Comment by dsafa** [comment]
Hmm, I haven't encountered this issue yet. I've been running spotify minimized with shuffle and have not come across this.

I guess we can try to narrow it down more and see if we can reproduce the issue.
1. What is your spotify version?
2. Does it happen with a specific playback type? (Playlist, daily mix, radio, etc.)
3. Does it occur when spotify plays the next song, or when you skip to the next song.
4. Are you still able to click on the next button in the toolbar / when you scrub through a song in spotify, does the track progress change in audio-band.

**Comment by medifin** [comment]
1. I'm using the latest version from Windows store. I recently had it with an older version, so I updated but the issue still persists.
2. I have been only listening to playlists so far.
3. It can happen in both situations, usually after 10-20 songs.
4. I'm able to click the buttons, but the song info or track progress does not change.

**Comment by medifin** [comment]
After a few hours of testing, it appears to be working fine for me now, thanks.
