### ISSUE TITLE
Text positioning resets to default on explorer.exe restart, or computer reboot

### ISSUE THREAD

**Issue by blizard-wizard** [dsafa/audio-band#206]
**Describe the bug**
After changing the default positioning of "text labels" they will reset to the default position after a reboot (crash of explorer.exe, or a logout also show same behavior). 
Issue does not affect other customizations of the labels. Only the positioning.

**To Reproduce**
1. Alter default positioning of a text label (I used the "artist" label, 140 width, 30 height, y=15, x=0)
2. Click on Apply to save changes
3. Reboot, logout, or end explorer.exe
4. Upon login the text positions will be reset (in the case of an explorer.exe restart, the positions will be reset without having to log back in.).

**Screenshots**
![image](https://user-images.githubusercontent.com/52839185/61157991-a5484400-a4c5-11e9-9361-1d84fdf56c36.png)

**Version Info**
 - Windows 10 Pro, 17763
 - AudioBand Version [v0.9.2]

**Logs attachment**
[AudioBand.log](https://github.com/dsafa/audio-band/files/3387978/AudioBand.log)

**Additional context**
Thank you kindly for this passion project. I hope this bug report helps you in creating a better program.

**Comment by dsafa** [comment]
Thanks. I can confirm the issue. It does appear to affect other label settings too.
