### ISSUE TITLE
The Spotify confirmation window pops up every time I start Windows

### ISSUE THREAD

**Issue by Elise4K** [dsafa/audio-band#207]
Ever since I changed my PC and reinstalled Windows, every time I boot into Windows, the "OK - This window can be closed now" Spotify confirmation window pops up. This did not happen in my old PC.

Screenshot
https://i.imgur.com/Wkr8wVz.png.

- Windows 10 Version 1903
- AudioBand 0.9.2

**Comment by dsafa** [comment]
There's some issue with the spotify settings not properly saving when the application closes. A workaround you can do is force a save by changing some setting and pressing apply.
