### ISSUE TITLE
AudioBand doesn't start 

### ISSUE THREAD

**Issue by Kyrust** [dsafa/audio-band#208]
When installed, AudioBand appears as an option in the taskbar menu, but clicking on it doesn't do anything (except opening an invisible folder "Deskband Host for wpf").

All the files are unblocked, I had a previous version (0.6.1) and i uninstalled it before installing the new one (0.9.2).
This happens on Windows 10 1903

[AudioBand.log](https://github.com/dsafa/audio-band/files/3389660/AudioBand.log)

EDIT: Apparently some stuff in the registry from the previous version was still hanging, i managed to solve it

EDIT 2: It only worked once and now i can't manage to show it again, probably the version that appeared that single time was the old one

**Comment by Kyrust** [comment]
I managed to solve this, but I had to install Audio Band with the .zip, so the problem still remains with the msi installer

**Comment by dsafa** [comment]
The issue is with old settings not properly being updated to the new version. I will get it  fixed. But if you are ok with it and don't mind, you can just delete old settings in `%appdata%/AudioBand/audioband.settings` and it will recreate default ones the next time it starts.
