### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Hanif89** [dsafa/audio-band#22]
![image](https://user-images.githubusercontent.com/9072028/45604686-685c1e00-ba69-11e8-8f87-25da22399e51.png)

Clicked the toolbar entry a few times, restarted explorer, restarted windows. Still doesn't show. No tick next to the toolbar entry in the taskbar menu. Am I missing something?

**Comment by mphartzheim** [comment]
I'm having the same issue. I'm not sure the warning displayed is related, though. I can install v0.5.1 and it works and I still get that same warning on install.

**Comment by dsafa** [comment]
Thanks for the report.
If it's not showing up after selecting it in the toolbars menu, then it's probably crashing at startup.

In your windows temp folder, there should be a file called AudioBand.log. If you can upload that, it would be great help.

**Comment by Hanif89** [comment]
[AudioBand.log](https://github.com/dsafa/audio-band/files/2395769/AudioBand.log)

**Comment by dsafa** [comment]
It seems that windows is blocking some files.  Try going to the installation folder and unblock the dlls that start with `Xceed`. for example `Xceed.Wpf.Toolkit` (Right click > Properties, then click unblock).

Let me know if that works or if its not even blocked in the first place.

**Comment by SAMUD** [comment]
I first copied the files to C:\Programme\AudioBand where I had the same problem. Unblocking didn't solve it. I had to move the files to my local Document-folder

**Comment by Earthtomars-GA** [comment]
unblocking didn't solve it and I'm not sure what to do

**Comment by MrUrf** [comment]
I have installed nearly every version of that pre-release (and of course I've deinstalled all of them after it failed) and I can't open it too. 
Sadly theres no Xceed  dll. 
[AudioBand.log](https://github.com/dsafa/audio-band/files/2729873/AudioBand.log)

**Comment by dsafa** [comment]
@MrUrf `Xceed` is not needed anymore. From your log it looks like there are issues loading some dlls. Make sure that they are all unblocked, even the ones in the `AudioSources` folder. Specifically for this case, unblock `iTunesAudioSource.dll` in the `AudioSources\iTunes` folder.

**Comment by dsafa** [comment]
Closing old issue. Newer versions have a different installation method that should prevent these issues.
