### ISSUE TITLE
Audio Band crashes Explorer.exe and restarts it

### ISSUE THREAD

**Issue by Bodroel** [dsafa/audio-band#220]
**Describe the bug**
As soon as I choose the AudioBand option in the toolbar menu it pops up for a second, freezes the Explorer and restarts it while removing the AudioBand toolbar.

**Checked common issues**
- [X] Unblocked the files. This is if you mean the unblock file in the zip folder

**To Reproduce**
Already stated in the bug description 

**Expected behavior**
That it works would be nice.

**Screenshots**
Added screenshot attachments
![A](https://user-images.githubusercontent.com/53445643/62071101-16b12200-b23c-11e9-9d35-50fb4c0efa45.PNG)
![B](https://user-images.githubusercontent.com/53445643/62071102-16b12200-b23c-11e9-9f13-e2a866eca65b.PNG)

**Version Info**
 - Windows 10 64bit
 - AudioBand Version V 0.9.3

**Logs attachment**
Added Logfile as attachment
[AudioBand.log](https://github.com/dsafa/audio-band/files/3443666/AudioBand.log)

**Comment by dsafa** [comment]
Try using the .msi installer instead of downloading the zip. The zip download shouldn't be there and I need to remove it. My bad for the confusion.

**Comment by Bodroel** [comment]
HEy man, thanks for the quick response. This fixed it for me!
