### ISSUE TITLE
Bottom part of song info text is cut

### ISSUE THREAD

**Issue by czaderak** [dsafa/audio-band#23]
Screenshot:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/ky3y1e/Bez_tytu_u.png" alt="Bez_tytu_u" border="0"></a>

**Comment by dsafa** [comment]
Thanks for the report.
What version are you running? If its on 0.6.1 can you open up the settings and screenshot the 'text labels' settings. 
Can you also try changing the settings like Font Size and Font family to get the text to fit. It's possible that the default settings don't work for everyone so I may need to change them.

Example of the settings im talking about:
![issuescreenshot](https://user-images.githubusercontent.com/7334282/45734842-c3416280-bb9a-11e8-82d7-f25bc8415b55.jpg)


Thanks

**Comment by czaderak** [comment]
I was able to fix it by changing "y position" and "height". I didn't know your app had so advanced settings. Thank you! :)
