### ISSUE TITLE
Can't make toolbar width fit to player

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [dsafa/audio-band#230]
Unlocking taskbar and changing width does not make a difference. 

Please can you advise? Thank you. 

![image](https://user-images.githubusercontent.com/44755101/65212534-6d97e280-da9a-11e9-9471-fe1951b0740a.png)

**Comment by dsafa** [comment]
If you want to resize the toolbar, you'll have to change the width under the general settings rather than trying to resize in the taskbar. Or is that what you already did? I might have misunderstood.

**Comment by My-Name-Is-Adam** [comment]
Thank you for the reply. 
If I make the width smaller it cuts everything on the right off. 
I've got it working now but have had to move all the elements over to the left manually.

https://i.imgur.com/i3p3Qqc.png

**Comment by dsafa** [comment]
Glad its working for you now. Yeah by default everything is positioned relative to the left. It might be better to have to relative to the right side by default instead. I've also seen some suggestions to make it easier to position things.
