### ISSUE TITLE
Seek bar doesn't work properly

### ISSUE THREAD

**Issue by luisgeraldes32** [dsafa/audio-band#237]
I'm in last version and all seems to be working good except when I click or drag the seekbar.
It's possible to click or drag but when clicked or released, the song is unaffected and then the seek bar returns to the correct current position.
This happens with spotify, ATM don't have another player to test it.
Preview:
![bug seekbar](https://user-images.githubusercontent.com/12972135/71624858-9de43680-2bdc-11ea-9901-3276d2f28a43.gif)

**Comment by svr333** [comment]
@luisgeraldes32 this happens because you don't have premium, and Spotify limits this feature to Premium only users.

**Comment by luisgeraldes32** [comment]
@svr333 did not knew that, maybe is a good idea indicating that in the documentation.
Thank you.
