### ISSUE TITLE
Menu not present after installation

### ISSUE THREAD

**Issue by stefanw1337** [dsafa/audio-band#244]
**Describe the bug**
Menus not present after installation.

**Checked common issues**
- [x] Unblocked the files. (Windows blocks files when installing / upgrading for some people)
- [ ] Double checked audio source specific issues (for audio source related issues)

**To Reproduce**
1. Install the newest .msi file.
2. Right click on the taskbar to select Audio Band from the toolbars submenu, only to find it's missing"

**Expected behavior**
I expected to be able to follow the documention in order to set it up:
1. Right click on the taskbar and select Audio Band from the toolbars submenu. (See images below)

**Screenshots**

**Version Info**
 - Microsoft Windows [Version 10.0.18363.752]
 - AudioBand-v0.9.4

**Logs attachment**
Audioband logs can be found in windows temp directory in the `AudioBand.log` file.
No such file found.

**Additional context**
Add any other context about the problem here. (e.g. occurs after upgrading to new version)

**Comment by stefanw1337** [comment]
Tried restarting PC, tried installing and choosing "Repair".

**Comment by olijoe** [comment]
I've had the same problem, you need to right click the task bar and need to activate audio band. taskbar > toolbars > audioband 
Then it should work.

**Comment by stefanw1337** [comment]
Oooh, I see, thanks. Bad instructions then :)
