### ISSUE TITLE
No functionality with MusicBee

### ISSUE THREAD

**Issue by Bout2GitIt** [dsafa/audio-band#252]
Describe the bug
When I select "Music Bee" from Audio Sources, nothing happens.  The checkmark moves to Music Bee, but the Audio Band continues to display art from Spotify, and the the buttons do nothing.

To Reproduce
Change Audio Band source to Music Bee

Expected behavior
Album art will change to current track in Music Bee, buttons will control Music Bee content.
![Screenshot_1](https://user-images.githubusercontent.com/45543439/84171903-54c8c600-aa49-11ea-8220-8c11c0afba40.png)
![Screenshot_3](https://user-images.githubusercontent.com/45543439/84171904-55615c80-aa49-11ea-8c21-476a194baa9e.png)

Screenshots

Version info:
Windows 10 Home Version 1909 OS Build 18363.836
Audio Band v 0.9.4

**Comment by eltoncezar** [comment]
Hi, did you followed the steps provided here?
https://dsafa.github.io/audio-band/audioband/audiosources/musicbee.html

**Comment by Bout2GitIt** [comment]
Ah, that was it. Thank you!
