### ISSUE TITLE
Album art and progress do not show up

### ISSUE THREAD

**Issue by kotobuki09** [dsafa/audio-band#26]
For some reason, the album and progress bar did not show up in my computer event I try to restart it a couple of time.  
![2018-10-02 19_14_51-](https://user-images.githubusercontent.com/34347264/46361901-7ddf6380-c677-11e8-92ee-d57c2dfb6c2a.png)

**Comment by Khillo81** [comment]
Can confirm. Progress bar and album art do not appear. However, this has been the case for the past couple of releases and has been acknowledged by the developer.

**Comment by dsafa** [comment]
That is correct. It should be fixed once I get around to fixing spotify issues. The only things that work right now are the song title and playback controls

**Comment by luisgeraldes32** [comment]
Idk if it was already fixed or not but my album art isn't showing, neither progress bar. Maybe something changed about spotify?

**Comment by dsafa** [comment]
Spotify is still being worked on

**Comment by dsafa** [comment]
Should now be working, fixed it in #32. Still some issues, I've posted a discussion here #39
