### ISSUE TITLE
Audio-band right-clicking taskbar range bigger then needed.

### ISSUE THREAD

**Issue by pascal0312** [dsafa/audio-band#260]
Hi there!

I got an interesting bug today, when right clicking the taskbar (next to audio-band) I keep getting the audio-band dropdown menu, not the windows taskbar dropdown menu. This happens for almost half my taskbar length.

I attached a screenshot of the issue, right side of the red line is audio-band territory, left side is taskbar territory. Red cross is my right-click position. As you can see, that's way further outside the audio-band visual and I expect to get the taskbar dropdown a few pixels left of the album art icon.

![audio-band](https://user-images.githubusercontent.com/39598246/87517759-9cadbf00-c67f-11ea-8fda-efb8eef4755b.png)

The screenshot is about half my original taskbar. 

**Version Info**
 - Windows version 10 Pro, 10.0.18363 
 - AudioBand Version 0.9.4

**Comment by eltoncezar** [comment]
Hi, I think you can solve this by setting the general width to a lower value. You can change it in the settings:
![image](https://user-images.githubusercontent.com/2071672/87596696-f4234d80-c6c6-11ea-805e-5627e942b133.png)

**Comment by pascal0312** [comment]
Oh, I am stupid.. When playing songs it's showing the title/artist.
![image](https://user-images.githubusercontent.com/39598246/87669396-2d62c880-c76e-11ea-8062-859e5d7bfc4a.png)

Solved, closed and ashamed.
