### ISSUE TITLE
Unusable space 

### ISSUE THREAD

**Issue by meekohhwhy** [dsafa/audio-band#266]
I have plenty of unusable space. Any program cannot be shown there because on ppm it shows AudioBand settings and sources.
![Zrzut ekranu 2020-10-20 190029](https://user-images.githubusercontent.com/73190460/96620685-0fc27380-1308-11eb-8739-26b2f5096b8d.png)
How to fix this?

**Comment by eltoncezar** [comment]
You need to change the general width of the widget. You can change it in the settings.
![image](https://user-images.githubusercontent.com/2071672/96634698-4214a680-12f1-11eb-86b8-698af02bc7d4.png)

**Comment by samwzlim** [comment]
![image](https://user-images.githubusercontent.com/74489037/103892252-3e413500-5126-11eb-86cb-43837b966b8d.png)
@meekohhwhy i've done as you said, but this happens instead
