### ISSUE TITLE
Empty Audio Source

### ISSUE THREAD

**Issue by a5haman** [dsafa/audio-band#3]
Hi there, first of, thank you for this! been searching everywhere for something like this!!

so apparently, Spotify does not appear when i click on Audio Source.

currently using the following
AudioBand-v0.3.0
Spotify Premium 1.0.77.338.g758ebd78

hope to get to use the final version soon! thank you.

**Comment by dsafa** [comment]
Is there a connectors folder in the directory where you unzipped the files? And is there a spotify subfolder in there.

**Comment by a5haman** [comment]
hi Brandon!

Yes, there is a connectors folder in the directory as well as a spotify
subfolder.




Mohd Husni
Wellness Coach | LifeStylist
[image: Live24 Studio] <http://www.live24studio.com>
[image: Live24 Studio] <http://www.live24studio.com/>

**Comment by dsafa** [comment]
Ok, thanks for reporting this.

Can you take a screenshot of the contents of the Spotify folder.

**Comment by a5haman** [comment]
Hello again Brandon,

Here's the screenshot as requested.



Thank you.

Husni

**Comment by dsafa** [comment]
The screenshot isn't showing up but its fine. What I really wanted to know is what is in the folder. There should be these three dlls
- Newtonsoft.Json
- SpotifyAPI
- SpotifyConnector

Also you are running 64 bit windows, correct?

**Comment by cvcore** [comment]
Hey @dsafa same issue here and heres a screenshot of my computer running Windows 10 x64.

I just unzipped the installation package and run the script w/ administrator permissions. Trying un- & reinstallation gives no help.

![20180602131118](https://user-images.githubusercontent.com/4695324/40871027-a74bc536-6666-11e8-98cc-6a3873598c8b.png)

![20180602131054](https://user-images.githubusercontent.com/4695324/40871029-ac34b774-6666-11e8-92a7-a50afe0029d2.png)

**Comment by ValdamireGido** [comment]
Same on my side. Using x64 system. connectors folder has spotify in it and all the needed files. May be we can give you some more info? Really want this thing to work. Great idea!

**Comment by dsafa** [comment]
Sorry for the late response, I've been busy.
Is there anti virus software that could be blocking it? We could try excluding the whole folder if that is the case.

Let me know, thanks.

**Comment by pascal0312** [comment]
I've tried excluding and disabling my anti-virus software (AVG). Source still stays empty.

**Comment by dsafa** [comment]
Ok, thanks for the confirmation.

I will add some logging to see if there are issues with finding the plugin location.

In the meantime can you try installing it in other locations.
thanks.

**Comment by madcaddies420** [comment]
![image](https://user-images.githubusercontent.com/40523737/41811629-36ae6c58-76e1-11e8-84dc-585d3aecbf77.png)
 Normal install message?

**Comment by madcaddies420** [comment]
Installing to another location does not work.

**Comment by dsafa** [comment]
Thanks for confirming.

The codebase argument is there because currently, I am not signing the assembly and installing into the GAC so I have to tell it the location of the files.

**Comment by gabrielscode** [comment]
Windows 10 Pro x64 - 21/08/2018
Audio Brand Settings open but...
The item "Audio Source" don't open or show any list...
I already updated the explorer, installed as administrator but it still does not work.

**Comment by dsafa** [comment]
In the latest version `0.5.0`, I've added logging to help fix this issue. After running audio band, there should be a `AudioBand.log` file in your Temp directory. If you open up the log file, there should be some lines that look like this:
```
2018-08-21 20:21:39.4063|DEBUG|AudioBand.AudioSource.AudioSourceManager|Searching for audio sources in path `S:\Code\audio-band\src\AudioBand\bin\Release\AudioSources`
2018-08-21 20:21:39.4693|DEBUG|AudioBand.AudioSource.AudioSourceManager|Found subfolder S:\Code\audio-band\src\AudioBand\bin\Release\AudioSources\spotify
2018-08-21 20:21:39.6652|DEBUG|AudioBand.AudioSource.AudioSourceManager|Audio source loaded: `Spotify`
```

If you can post that, it will help a lot.
Thanks.

**Comment by gabrielscode** [comment]
The file "AudioBand.log" was not generated in the folder "C:\Windows\Temp".
(running as administrator)

**Comment by pascal0312** [comment]
Hey there,

I installed it again and gave it a few tries.
Running as admin, restarted PC before and after installation.
Audio source is still empty.

Log says:
```
2018-08-23 00:26:29.0594|DEBUG|AudioBand.AudioSource.AudioSourceManager|Searching for audio sources in path `C:\Users\Pascal\Desktop\AudioBand-v0.5.0\AudioSources`
2018-08-23 00:26:29.0844|DEBUG|AudioBand.AudioSource.AudioSourceManager|Found subfolder C:\Users\Pascal\Desktop\AudioBand-v0.5.0\AudioSources\spotify
```

Apparently the problem is loading the source?

**Comment by corzone** [comment]
Apparently this worked out for me so that now it appears the audio source and it can play it.As the files came from the internet and it is a strange file to windows, it blocks it from being executed by the audioband.So what you need to do is go to the«audiosources» folder from the folder of the audioband installer/unistaller and unblock individual the 3 files that are inside and that should be enough to work.
Ps:Maybe necessary to restart the windows explorer so that it works
PsPs:unblock the files(for the newbies):file»right mouse button»properties»unblock»apply
Hope it helped

**Comment by pascal0312** [comment]
I wanted to try @corzone 's solution, but I only had my laptop with me. I didn't had to try the unblocking part, it already worked. I just don't see an image album or song title/artist. I can however use the back, play/pause and next buttons.

**Comment by dsafa** [comment]
@corzone  Thanks for finding out the problem and solution. We'll see if other people can confirm this.

@pascal0312 The no album / song information is due to #17

**Comment by themtilhan** [comment]
@dsafa I tried the solution and it worked but just like @pascal0312 i can't use play button only next song and previous song works. I also tried to unblock every file inside of the folder but still not working play button.

**Comment by dsafa** [comment]
@pascal0312 and @themtilhan The play / pause issue is also due to the Spotify issue. I've put a workaround in the newest version (0.5.1) for this so most things are working again. I've put more information in the other issue #17

**Comment by themtilhan** [comment]
@dsafa yes thank you very much. I tried new version now and when I unblock those three API dlls inside of AudioSources\spotify it works completely fine now.

**Comment by dsafa** [comment]
Looks like its fixed and I've added this information to the readme so people won't have to search for this issue anymore.
