### ISSUE TITLE
Audioband 0.7.0 Spotify

### ISSUE THREAD

**Issue by dsafa** [dsafa/audio-band#39]
I've moved audioband to use the official Spotify api so now things are working again. However it's not without any problems. (Copy pasted from readme):
- ~~The browser will show up everytime audioband starts asking you to log into Spotify. Even if you select remember me, a browser window still opens. This will be fixed in a later version.~~ Fixed in (0.7.1)
- The song progress will be out of sync if you change the song's progress. This is due to current limitations making the song progress being tracked locally. This can be fixed if you pause and play again or go to a different song.
- The first time you open up Spotify, the current song may not be displayed. This is because Spotify doesn't report any song information if you have no devices playing songs. Just start playing a song and it will start displaying.
- ~~Sometimes, the updates stop and you have to deselect and reselect spotify as the audio source. #49~~

I'm putting this issue to notify and for discussions of new issues. Also for clarifications about the new changes.

**Comment by d-makarenko** [comment]
Hi! Thank you, it is a great work!
I have some problems though. When I am trying to authorize AudioBand, I am getting 
```INVALID_CLIENT: Invalid redirect URI```
response from Spotify. 

So, I added redirect url in the Spotify API Application settings:
```
http://localhost
```
Now it kinda works. I am getting authorization screen and after I press Okay button, I get response from AudioBand:
```
OK - This window can be closed now
```
But,  the redirect url contains access_denied error:
```
http://localhost/?error=access_denied&state=598a3bc4
```
And AudioBand panel shows nothing.

**Comment by d-makarenko** [comment]
Well, I notice that there is no `client_secret` in the auth request url. I modified URL and it looks like authorization was successful and Spotify returned authorization code in response. 
But now Explorer is constantly crashing so I need to unregister Audio Band panel.

**Comment by d-makarenko** [comment]
```
System.Net.Http.HttpRequestException was unhandled
Message: An unhandled exception of type 'System.Net.Http.HttpRequestException' occurred in mscorlib.dll
InnerException: 407 Proxy Authentication Required.
```

**Comment by dsafa** [comment]
Crashing is pretty bad. When I get #1 done crashes should no longer crash explorer. As for the proxy, I'll look into it. I'm using a library to connect to Spotify and I believe I saw an example using proxy settings.

**Comment by tylrbvn** [comment]
> Well, I notice that there is no `client_secret` in the auth request url. I modified URL and it looks like authorization was successful and Spotify returned authorization code in response.
> But now Explorer is constantly crashing so I need to unregister Audio Band panel.

I've had the same issue with the missing client secret in the URL, adding manually resolved for me (haven't experienced any crashes yet)

**Comment by ereiwin** [comment]
Hello, I have INVALID_CLIENT: Invalid Client when I launch Audio Band in the windows bar.

The redirection is:
https://accounts.spotify.com/authorize/?client_id=myemail@gmail.com&response_type=code&redirect_uri=http://localhost&state=602463f9&scope=user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing&show_dialog=False

I've tried to add the client_secret parameter but it's not working:
https://accounts.spotify.com/authorize/?client_id=myemail@gmail.com&client_secret=password&response_type=code&redirect_uri=http://localhost&state=574c477a&scope=user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing&show_dialog=False

Is it the correct parameters?

**Comment by ereiwin** [comment]
> @ereiwin Your client ID looks wrong, it shouldn't be an email address but a 32 char long ID, e.g. ea194f9bb2c04c05e9ff58a9bf1f43d0, for the app you created in your Spotify dashboard (see https://github.com/dsafa/audio-band#spotify-setup)

Thank you and sorry I didn't see the hole instructions at the 1st time. I now have the "OK - This window can be closed now" message after saving the audio source settings and I've add the "client_secret" parameter to the URL do don't have the error.
But Audio Band panel is empty even after skipping the first songs.

**Comment by dsafa** [comment]
Thanks for the reports. There is a problem if it wasn't set up correctly the first time. should be getting fixed soon.

**Comment by dsafa** [comment]
Latest version `0.7.1` should no longer open up the browser after authenticating successfully.
Also important to note is that the callback url has changed from `http://localhost` to `http://localhost:80`.
There is still a random freezing/no updates issue but I at least know what is causing it.

**Comment by dsafa** [comment]
Closing old issue
