### ISSUE TITLE
Resize settings window

### ISSUE THREAD

**Issue by pascal0312** [dsafa/audio-band#40]
Hey there, just started using 7.0. Works like a charm! Well done!

Only thing is, now that I used the settings window a few times, it keeps opening up a bit larger than the height of my screen.
If you could resize it to maybe half that size, that would be great. Not every tab needs that much space, and it seems it takes the biggest size, the playback controls, as a base.

**Comment by dsafa** [comment]
Yeah I need to cut it down. I just used the default font sizes.

**Comment by dsafa** [comment]
The settings UI has been redone in the latest version `0.7.1` and takes up less space.
