### ISSUE TITLE
Album art, pause, track title & progress

### ISSUE THREAD

**Issue by bphillips79** [dsafa/audio-band#41]
So this might be old news, but I've also seen that it was fixed so I'm not sure.  I just installed tonight for the first time.  After getting all the files finally unblocked, I was able to start the toolbar and add Spotify as the source.  Went into the audio band options and pasted in the client numbers from the dashboard.  I put the local url in the "redirect url" in the Spotify dashboard.  When I did, I got this in a new browser window:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
Additionally, I'm not getting album art, track title, progress bar, or pause.  The previous, next, and play work though.  I've attached a screen shot and a log file.  Any help would be appreciated.  I've been looking for something like this for years.

![spotify screenshot](https://user-images.githubusercontent.com/44659888/47832977-d127fd00-dd6e-11e8-8ff2-9a8ed490ef2d.png)
[AudioBand.log](https://github.com/dsafa/audio-band/files/2537230/AudioBand.log)

**Comment by Khillo81** [comment]
Normally, the browser window should open with a Spotify log-in page. There's an error somewhere. Are you adding `http://localhost` to the "redirect url" field? If so, could you try `http://localhost:8000`? For me, everything is working as it should: 
![image](https://user-images.githubusercontent.com/9437760/47873951-d0e13d80-de12-11e8-9f76-0b52279790ce.png)

**Comment by bphillips79** [comment]
Thanks for getting back to me.  I went into the dashboard, removed the old link, pasted in the one you wrote.  I rebooted and this message came up when I logged into windows:
`INVALID_CLIENT: Invalid redirect URI`
Additionally, the buttons are no longer functioning.  I'll add the local host back (leaving both in) and will reboot to see what happens.

**Comment by bphillips79** [comment]
Another update.  Completely removed the files and deleted the entry in the dashboard.  Reinstalled and set up a new app in the dashboard.  After rebooting, got the browser prompt to log in.  Did so, and the screen refreshed to the JSON error again.

**Comment by dsafa** [comment]
I've seen a JSON parse error before but not inside a browser window. I'll investigate.

**Comment by dsafa** [comment]
The json parse error comes from spotify sending html in their 5xx errors instead of json. Not much that can be done other than adding a delay and re-sending the request.
