### ISSUE TITLE
Album art + song freeze

### ISSUE THREAD

**Issue by pascal0312** [dsafa/audio-band#42]
After (random) intervals Audio Band seems to stop working. The album+song stay the same. I can pause the music with the app, but I can't play it after.
Either the connection to spotify is lost or the app stops working.

If I deselect spotify as source and select it again the browser window opens, I login and the art updates again. Hello working app!

E: After some testing I might've found the issue. The Play/Pause button won't switch. I can skip to the next song or pause it. Just not play.. Album art still stays the same though.

**Comment by bphillips79** [comment]
Same for me, but I get a JSON error (#41 ) instead of the log in screen.

**Comment by dsafa** [comment]
I'll look into it. It's probably as you said and the connection is timing out or the access token expiring.

**Comment by luisgeraldes32** [comment]
Mine happened a few times too. Only (sometimes) deactivating and reactivating Audioband toolbar gets to work again.
"Fixed it" partially reverting to 0.6.2 (without progess bar and album art) but at least the controllers and song artist/title allways work.

**Comment by dsafa** [comment]
The random freezing is fixed now in `v0.7.3` (#55).
