### ISSUE TITLE
Export & import layout configs

### ISSUE THREAD

**Issue by ingdanko** [dsafa/audio-band#44]
Suggestion: ^^title
I think it would be pretty neat if we could share our customized toolbars.

**Comment by dsafa** [comment]
The settings file does exist in `AppData\Roaming\AudioBand` but I haven't put a export/import button yet.

**Comment by luisgeraldes32** [comment]
Hello, I know this is maybe in progress but I would suggest something else.
Instead an import/export button only, what about a layout chooser from a list? We could possibly use put multiple layouts in the folder and then choose the one we like the most. (I'm thinking changing layouts quickly when someone gets tired of allways the same).
Also, is it possible to share the layouts you've got in your screenshots?

Thank you.
