### ISSUE TITLE
Explorer Freezes when select iTunes

### ISSUE THREAD

**Issue by luisgeraldes32** [dsafa/audio-band#62]
Hello,
I'm trying the new 0.7.6 version (works flawlessly with Spotify and iTunes until now).
I would like to report a small bug:
When select iTunes as an audio source WITHOUT iTunes opened, the explorer freezes and need to restart the explorer process. When already opened, I can select iTunes or Spotify (didn't tried Music Bee) that works perfectly fine.
Thank you.

**Comment by dsafa** [comment]
When I was testing, itunes would automatically open when you selected it and it did freeze for a bit while itunes was loading. How long did you wait when explorer was frozen?

**Comment by luisgeraldes32** [comment]
Ah, I've tried it right now. The explorer freezes a little bit but it's really opening iTunes.
Probably when I clicked, I've assumed the explorer freezes and restarted right away. Now I see iTunes opens.
Still, the taskbar becomes frozen for a moment until iTunes opens.

**Comment by dsafa** [comment]
Good to know. I can't keep itunes from opening but I should be able to not make explorer freeze.

**Comment by dsafa** [comment]
Closing for now since I can't change the behavior of the iTunes COM interop
