### ISSUE TITLE
Pressing tab when editing values in settings glitches out the window

### ISSUE THREAD

**Issue by ingdanko** [dsafa/audio-band#71]
Bug?: Title^^
Not sure if it's a Windows 10 thing, or if it's fixable. Maybe you can figure it out.

**Comment by dsafa** [comment]
What kind of glitching is it? When I press tab, it switches focus out of the settings window which is probably not the excepted behaviour. Not sure if that's the same thing you are talking about.

**Comment by mendelsimon** [comment]
Pressing tab appears to focus the first item in my windows taskbar.
