### ISSUE TITLE
Toolbar Not Showing (v 0.7.6)

### ISSUE THREAD

**Issue by TheMik3n** [dsafa/audio-band#74]
I've installed v. 0.7.6 and cannot get the Audioband toolbar to show. I've run the unblock script, restarted both my computer and windows explorer, have Audioband selected under toolbars, and have Spotify launched. Any idea what might be going on?
[AudioBand.log](https://github.com/dsafa/audio-band/files/2783345/AudioBand.log)

**Comment by dsafa** [comment]
Closing old issue as it relates to older version of audioband. Feel free to reopen if the issue exists on newer versions.
