### ISSUE TITLE
Song time bar not updating on 'previous song' when paused

### ISSUE THREAD

**Issue by ingdanko** [dsafa/audio-band#78]
After clicking 'previous song' when a song is midway to play it from the beginning, if the song is paused, the progress bar does not update.

(Spotify)

How to reproduce:
1) Play a song
2) Skip to about a half of the song's length
3) Press 'Previous song'
The progress (song time) bar does not update.

**Comment by ingdanko** [comment]
The progress bar is not resetting to 0 (start of song) is what I was trying to say, so even if Spotify doesn't give the information, the fix shouldn't be difficult.

**Comment by dsafa** [comment]
Currently I can't detect any changes in the progress within the same song. I only get the latest information when the song changes or it goes from play to pause and vice versa. But I do have an idea for a workaround now since you reminded me.
