### ISSUE TITLE
Support for font icons on playback controls

### ISSUE THREAD

**Issue by adk2266** [dsafa/audio-band#79]
It would be very convenient to support icon fonts in addition to raster images as the icons for the playback controls.  
I just changed my playback icons to those from the Segoe MDL2 icon set so they would fit better with Windows 10's look, and found it suprisingly complicated, as the icon set is only provided as a font so I had to copy each character into an image editor, then export it to a png to use in AudioBand.  Even so they don't look perfect because they're raster images and I didn't get the size exactly right.
It would be very nice and convenient if Audioband could directly use the icons from the font

**Comment by dsafa** [comment]
Good idea. I'll take a look into it.
