### ISSUE TITLE
No song / album info showing [Controls still work]

### ISSUE THREAD

**Issue by KuDoZ007** [dsafa/audio-band#8]
Appears on current Windows Store Spotify version (1.0.80.474.gef6b503e) with latest Windows Version	10.0.17134 Build 17134 that no song / album info is being shown.

The control buttons still work though! :)

**Comment by dsafa** [comment]
Thanks for reporting.

Can you attach a screenshot?
Also in the **temp** folder (default location: C:\Users\**username**\AppData\Local\Temp) there should be a file called AudioBand.log. Can you also attach that too, thanks.

**Comment by dwc7988** [comment]
I am having the same issue...here is what you requested.
[AudioBand.log](https://github.com/dsafa/audio-band/files/2219491/AudioBand.log)
![capture](https://user-images.githubusercontent.com/41580345/43079528-f48f4034-8e52-11e8-96e6-8917ef4d3105.JPG)

**Comment by dsafa** [comment]
I apologize, I forgot to reply to this but the issue was because Spotify's api was not activated. This issue should be fixed with the recent Spotify changes.  If it is still there I can reopen the issue.
