### ISSUE TITLE
Option to stop text scroll when music paused

### ISSUE THREAD

**Issue by mendelsimon** [dsafa/audio-band#85]
I noticed that the scrolling text would catch my eye even when the music wasn't playing. 
I think it would be nice if there was an option in the Text Label configuration to stop scrolling when the music isn't playing (with the text either pausing in the current position or jumping to the original position). 

_Unrelated: I love this project. Thank you @dsafa for all of your hard work!_

**Comment by dsafa** [comment]
Thanks, I've got plans for better scrolling options which will include this.

**Comment by dsafa** [comment]
Closing done issues
