### ISSUE TITLE
Spotify local tracks not showing in toolbar 

### ISSUE THREAD

**Issue by TobyHawkes** [dsafa/audio-band#87]
Hi,

I noticed that when a track played from spotify that is a local only file that the toolbar doesn't show the artist - title, or just displays the last spotify track instead.

The https://api.spotify.com/v1/me/player/currently-playing endpoint does have the ability to show local track details as I'm using this in one of my own projects

**Comment by dsafa** [comment]
Thanks for the report. I have the fix for this.

**Comment by TobyHawkes** [comment]
all working now, thanks
