### ISSUE TITLE
Appears on taskbar and can open settings & sources, but doesn't work

### ISSUE THREAD

**Issue by brownmatthewwm** [dsafa/audio-band#97]
As per title. This is my first install of Audio Band, so I don't know what it's like when it does work.

Before running the unblock script, it appeared on the taskbar. I could right-click and the settings and source selection would appear in the dropdown, but I couldn't expand the source selection menu or open settings.
After running the unblock script, I could access the settings and pick an audio source (Spotify), but nothing is displayed but an underscore and the media controls still don't work.

Sharing music activity is on, if that matters. I checked my firewall settings and all the listings related to Spotify were allowed to communicate on both private and public networks. I normally use the Windows Store verison of Spotify, but I also tried it with Spotify Windows Desktop - I don't know whether that matters either, as they appear to be identical.

Audio Band version: 0.7.9
OS version: Windows Personal v1809, build 17763.316
Spotify versions: 1.1.0.237.g378f6f25 on both desktop and Microsoft Store versions
Machine: Lenovo Yoga 730 (2018)

cmd output:
RegAsm : warning RA0000 : Registering an unsigned assembly with /codebase can cause your assembly to interfere with other applications that may be installed on the same computer. The /codebase switch is intended to be used only with signed assemblies. Please give your assembly a strong name and re-register it.
Succesfully registered deskband `Audio Band` - GUID: {957d8782-5b07-4126-9b24-1e917baaad64}
Request to show deskband.
Types registered successfully
Press any key to continue . . .

Logs (parts of them are in French, sorry):
[AudioBand.1.log](https://github.com/dsafa/audio-band/files/2895232/AudioBand.1.log)
[AudioBand.log](https://github.com/dsafa/audio-band/files/2895233/AudioBand.log)
[AudioBand.0.log](https://github.com/dsafa/audio-band/files/2895234/AudioBand.0.log)

Screenshot of Spotify settings:
![capture d ecran 21](https://user-images.githubusercontent.com/3986375/53262907-7c055380-369d-11e9-8a70-542d38097333.png)

**Comment by mendelsimon** [comment]
You need to register Audio Band on your Spotify dashboard and then sign in.
The instructions are laid out here: https://dsafa.github.io/audio-band/audioband/audiosources/spotify.html

**Comment by brownmatthewwm** [comment]
Thanks for the prompt reply! Everything works properly now.

Le ven. 22 févr. 2019 à 13:43, Mendel Simon <notifications@github.com> a
écrit :

**Comment by Jazzman1976** [comment]
I don't get the connection... when I come to the point where my audio band settings are saved and the browser opens, I can click OK but than the redirect to my localhost doesn't work.
I tried Port 80 and 8080 - nothing happens.
I used the Spotify App and the Webplayer - nothing.
Is there any way to set another domain listening? Maybe an issue with the localhost... I use the IIS as webserver, too.

**Comment by Jazzman1976** [comment]
OK - After removing the Audio Band and adding it again it is working! Yeah ;-)
